[tool.poetry]
name = "network"
version = "0.1.0"
description = ""
authors = ["Hubert Zajac <hubertzajac6@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mypy = "^1.2.0"


[tool.mypy]
namespace_packages = true
check_untyped_defs = true
disallow_untyped_defs = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
