# This workflow will build and push docker image to the docker hub.

name: Check regression

on:
  pull_request:
    types: [ labeled ]

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.event.label.name == 'RUN_ALL_TESTS' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: |
          docker build -t network .

      - name: Check regression
        run: |
          docker run network pytest tests --template=html1/index.html --report=report.html -n auto

      - uses: actions/github-script@v6
        with:
          script: |
            const issue_num = context.payload.project_card.content_url.split('/').pop()
            github.rest.issues.removeLabel({
              issue_number: issue_num,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["RUN_ALL_TESTS"]
            })

